apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hemliga-lappen
  name: hemliga-lappen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hemliga-lappen
  strategy:
  template:
    metadata:
      labels:
        app: hemliga-lappen
        team: team-devops
        unit: developers
    spec:
      containers:
        - image: harbor.tools.ur.se/team-devops/hemliga-lappen
          imagePullPolicy: Always
          name: hemliga-lappen
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
