apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hemliga-lappen-stage-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hemliga-lappen
      team: team-devops
      unit: developers
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: hemliga-lappen-deployment
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - analysis:
          templates:
          - templateName: always-pass
            clusterScope: true
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}

      canaryService: hemliga-lappen-stage-canary #required
      stableService: hemliga-lappen-service  # required
      trafficRouting:
        nginx:
          stableIngress: hemliga-lappen-ingress
          additionalIngressAnnotations:   # optional
            nginx.ingress.kubernetes.io/canary: "true"
            canary-by-header: X-Canary
            canary-by-header-value: canary
          ignoredAnnotations:
            - field.cattle.io/publicEndpoints