apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hemliga-lappen-stage-rollout
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: argoCD-test-channel-1;argoCD-test-channel-2
    notifications.argoproj.io/subscribe.on-rollout-updated.slack: argoCD-test-channel-1;argoCD-test-channel-2
    notifications.argoproj.io/subscribe.on-rollout-updated.github: ""
    notifications.argoproj.io/subscribe.on-rollout-step-completed.github: ""
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hemliga-lappen
      team: team-devops
      unit: developers
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: hemliga-lappen-deployment
  strategy:
    canary:
      canaryService: hemliga-lappen-stage-preview
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}